module.exports = {
    roots: ['<rootDir>/src'],
    collectCoverageFrom: [
        '<rootDir>/src/**/*.ts',
        '!<rootDir>/src/server.ts',
        '!<rootDir>/src/domain/**',
        '!<rootDir>/src/main/**',
        '!<rootDir>/src/tests/**',
        '!<rootDir>/src/**/Fake*.ts',
        '!<rootDir>/src/utils/errors/**',
        '!<rootDir>/src/infra/database/helpers/typeOrm/**',
        '!<rootDir>/src/infra/database/config/typeOrm/**',
        '!<rootDir>/src/infra/database/migrations/typeOrm/**',
    ],
    displayName: 'root-tests',
    coverageDirectory: 'coverage',
    testEnvironment: 'node',
    clearMocks: true,
    preset: 'ts-jest',
    transform: {
        '.+\\.ts$': 'ts-jest',
    },
    moduleNameMapper: {
        '@data(.*)': '<rootDir>/src/data/$1',
        '@domain(.*)': '<rootDir>/src/domain/$1',
        '@infra(.*)': '<rootDir>/src/infra/$1',
        '@main(.*)': '<rootDir>/src/main/$1',
        '@presentation(.*)': '<rootDir>/src/presentation/$1',
        '@utils(.*)': '<rootDir>/src/utils/$1',
        '@tests(.*)': '<rootDir>/src/tests/$1',
    },
};
